[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# Send API requests to the Express app wrapped by serverless-http
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
